name: Automated tests

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    steps:
      - uses: actions/checkout@v4
      - name: Setup Redis
        uses: zhulik/redis-action@1.1.0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore
      - name: Pack nugets
        run: dotnet pack -c Release --output .
      - uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: |
            *.nupkg
            *.snupkg
